### PR TITLE
TESmart serial port support for kvmctl

### PR DESCRIPTION
**Pull request by TripleEmcoder**
Managed to make my PiKVM talk to TESmart 16-port over serial - PiKVM console port breakout to the "proprietary" TX/RX port on the KVM. I wasn't comfortable exposing the KVM on LAN, this felt more secure and integrated. Though I would share the resulting script. The PR is split into 3 commits to show the exact changes. It might be nice to integrate both scripts back together and add a protocol parameter, but I don't think I will be spending much more time on this (apart from fixing bugs if such arise). There probably isn't a real need to switch protocols in the same deployment once you get the connection up and running.

### CODE REVIEW

**Comment by bbeaudoin** [comment]
No objections but, given all commands are sent in a single function, I might instead recommend a flag or keying off a device name to determine how the command is sent such as follows:

```
# Port is an overloaded term, may prefer to use "DEVICE" or for the serial /dev/ instead
DEVICE="/dev/ttyAMA0"
BAUD=9600
[...]

function sendCommand {
  # While socat wait time is 0.5s, this can and does fail if we don't sleep first
  sleep 1

  # Preamble AABB03 + Token/Value + EE
  output=$(echo -e "AABB03${1}EE" | xxd -r -p)
  
  # Send to serial or via network depending on device
  if [ ! -z "DEVICE" ]; then
    echo $output | socat - $DEVICE | hexdump -v -e '/1 "%02X"' || echo ff
  else
    echo $output | nc ${ADDRESS} ${PORT} | xxd -s4 -l1 -p 2>/dev/null || echo ff
  fi

  # Note whatever output is printed is the `return` value. If communication
  # fails, the logical `or` with `|| echo ff` ensures an expected hex value
  # is always included, this may be replaced with another hex value to
  # indicate failure
}
```

Without testing, I'm pretty sure `hexdump -v -e '/1 "%02X"'` and `xxd -s4 -l1 -p 2` have similar, if not identical, output. Regardless, this is only used to help inform the user as to the status. The `|| echo ff` was added as sometimes TESmart sometimes fails, this ensures the calling function always receives an expected hex code on return.

Please consider modifying your pull request to change the base script to handle both methods. Given the majority of the code is common aside from the method by which the string is sent, it makes sense to make incremental changes to the base script rather than maintain two scripts that are otherwise identical.

**Comment by TripleEmcoder** [comment]
Thanks for the instant feedback. You are of course correct on all accounts. There were more differences in the script along the way, but in the end the it did turn out almost identical. I will merge my changes back into the original. One thing though, do you have a way to reproduce the problems that are solved with sleep? I've been sending commands over serial in series and seen no issues at all. Maybe this is TCP specific, maybe there is a delay before the switch starts to listen for new connections after the last one closes?

**Comment by bbeaudoin** [comment]
Yes, when sending repeated commands the TESmart might not respond as expected. Normally it responds in all cases with the current port number. `socat` might not suffer from this but netcat (`nc`) might not wait long enough or the IP-to-serial adapter might be introducing errors that aren't present with a direct serial connection.

It is possible to maintain a consistent connection with constant feedback, that is a potential improvement on the simple script. It's also the reason I request the port prior to sending a setting, that does seem to help along with the sleep. If direct serial doesn't have this issue, the sleep can be moved to the case that handles the network transmission instead.

**Comment by TripleEmcoder** [comment]
Merged as promised. I left sleep only on the network path, couldn't reproduce any issues over serial. Also added an additional check to verify TESmart's response has the correct pattern so we don't try to interpret something else.

**Review by bbeaudoin — COMMENTED** [review]
LGTM

**Pull request merged**
